### ISSUE TITLE
Extract strings into PO

### ISSUE THREAD

**Issue by zoltanmagyar** [eusonlito/laravel-Gettext#2]
Hi Lito,

the package looks really great, but I can't figure out how to generate PO files.
I'm relatively new to gettext translations, so maybe it's obvious to someone more advanced.
If You'd add some comments in the code or extend the readme.md a little bit it would be a great help.

Thank You!

**Comment by eusonlito** [comment]
You can generate PO files using for example [Poedit](https://poedit.net/).

Create your proyect, use Poedit to scan file and discover strings to translate and save it into storage/gettext/xx_XX/LC_MESSAGES/

You have a detailed explanation here: http://www.pontikis.net/blog/php-javascript-internationalization-gettext-poedit

**Comment by joucogi** [comment]
I have a problem when I generate PO files.
When I generate PO files using Poedit because that program doesn't extract string from tag's attributes.

Examples:
`<h1>{{ _e('Title'); }} </h1>  <-- No problem, extract string correctly`
`<button title="{{ _e('Edit' )}}"><i class="fa fa-edit"></i></button> <-- Doesn't extract the string from attribute title`


Any suggest?

Thank you
